/*
	File: fn_varHandle.sqf
	Author: Bryan "Tonic" Boardwine
	
	Description:
	Master handler for getting a variables name, short name, etc.
*/
private["_var","_mode"];
_var = [_this,0,"",[""]] call BIS_fnc_param;
_mode = [_this,1,-1,[0]] call BIS_fnc_param;
if(_var == "" OR _mode == -1) exitWith {""};

switch (_mode) do
{
	case 0:
	{
		switch (_var) do
		{
			case "oilu": {"life_inv_oilu"};
			case "oilp": {"life_inv_oilp"};
			case "heroinu": {"life_inv_heroinu"};
			case "heroinp": {"life_inv_heroinp"};
			case "cannabis": {"life_inv_cannabis"};
			case "marijuana": {"life_inv_marijuana"};
			case "apple": {"life_inv_apple"};
			case "water": {"life_inv_water"};
			case "rabbit": {"life_inv_rabbit"};
			case "salema": {"life_inv_salema"};
			case "ornate": {"life_inv_ornate"};
			case "mackerel": {"life_inv_mackerel"};
			case "tuna": {"life_inv_tuna"};
			case "mullet": {"life_inv_mullet"};
			case "catshark": {"life_inv_catshark"};
			case "turtle": {"life_inv_turtle"};
			case "fishing": {"life_inv_fishingpoles"};
			case "coffee": {"life_inv_coffee"};
			case "turtlesoup": {"life_inv_turtlesoup"};
			case "donuts": {"life_inv_donuts"};
			case "fuelE": {"life_inv_fuelE"};
			case "fuelF": {"life_inv_fuelF"};
			case "money": {"life_cash"};
			case "pickaxe": {"life_inv_pickaxe"};
			case "copperore": {"life_inv_copperore"};
			case "ironore": {"life_inv_ironore"};
			case "iron_r": {"life_inv_ironr"};
			case "copper_r": {"life_inv_copperr"};
			case "salt": {"life_inv_salt"};
			case "salt_r": {"life_inv_saltr"};
			case "sand": {"life_inv_sand"};
			case "glass": {"life_inv_glass"};
			case "tbacon": {"life_inv_tbacon"};
			case "lockpick": {"life_inv_lockpick"};
			case "redgull": {"life_inv_redgull"};
			case "peach": {"life_inv_peach"};
			case "diamond": {"life_inv_diamond"};
			case "diamondc": {"life_inv_diamondr"};
			case "cocaine": {"life_inv_coke"};
			case "cocainep": {"life_inv_cokep"};
			case "spikeStrip": {"life_inv_spikeStrip"};
			case "cement": {"life_inv_cement"};
			case "rock": {"life_inv_rock"};
			case "goldbar": {"life_inv_goldbar"};
			case "blastingcharge": {"life_inv_blastingcharge"};
			case "boltcutter": {"life_inv_boltcutter"};
			case "defusekit": {"life_inv_defusekit"};
			case "storagesmall": {"life_inv_storagesmall"};
			case "storagebig": {"life_inv_storagebig"};
			
			case "shovel": {"life_inv_shovel"};
			case "stolenJewelry": {"life_inv_stolenJewelry"};
			case "ziptie": {"life_inv_ziptie"};
			case "burger": {"life_inv_burger"};
			case "sburger": {"life_inv_sburger"};
			case "ffries": {"life_inv_ffries"};
			case "cola": {"life_inv_cola"};
			case "cshake": {"life_inv_cshake"};
			case "cabsav": {"life_inv_cabsav"};
			case "merlot": {"life_inv_merlot"};
			case "shiraz": {"life_inv_shiraz"};
			case "grenache": {"life_inv_grenache"};
			case "pinotnoir": {"life_inv_pinotnoir"};
			case "chardonnay": {"life_inv_chardonnay"};
			case "souvblanc": {"life_inv_souvblanc"};
			case "semillon": {"life_inv_semillon"};
			case "riesling": {"life_inv_riesling"};
			case "guiness": {"life_inv_guiness"};
			case "bwheat": {"life_inv_bwheat"};
			case "cblue": {"life_inv_cblue"};
			case "bmoon": {"life_inv_bmoon"};
			case "sablager": {"life_inv_sablager"};
			case "vbitter": {"life_inv_vbitter"};
			case "tnew": {"life_inv_tnew"};
			case "told": {"life_inv_told"};
			case "clager": {"life_inv_clager"};
			case "cale": {"life_inv_cale"};
			case "oempire": {"life_inv_oempire"};
			case "jaipur": {"life_inv_jaipur"};
			case "spetersburg": {"life_inv_spetersburg"};
			case "hhoney": {"life_inv_hhoney"};
			case "portstout": {"life_inv_portstout"};
			case "sbbitter": {"life_inv_sbbitter"};
			case "moonshine": {"life_inv_moonshine"};
			case "scotch": {"life_inv_scotch"};
			case "whiskey": {"life_inv_whiskey"};
			case "brandy": {"life_inv_brandy"};
			case "vodka": {"life_inv_vodka"};
			case "tequila": {"life_inv_tequila"};
			case "sake": {"life_inv_sake"};
			case "whiterum": {"life_inv_whiterum"};
			case "rum": {"life_inv_rum"};
			case "gin": {"life_inv_gin"};
			case "absinthe": {"life_inv_absinthe"};
			case "aids": {"life_inv_aids"};
			case "roadCone": {"life_inv_roadCone"};
			case "roadBarrier": {"life_inv_roadBarrier"};
			case "cautionTape": {"life_inv_cautionTape"};
			case "campFire": {"life_inv_campFire"};
			case "sleepbagGreen": {"life_inv_sleepbagGreen"};
			case "sleepbagBlue": {"life_inv_sleepbagBlue"};
			case "sleepbagBrown": {"life_inv_sleepbagBrown"};
			case "tentRidge": {"life_inv_tentRidge"};
			case "tentDome": {"life_inv_tentDome"};
			case "portGenerator": {"life_inv_portGenerator"};
			case "bagfenceShort": {"life_inv_bagfenceShort"};
			case "bagfenceLong": {"life_inv_bagfenceLong"};
			case "bagfenceRound": {"life_inv_bagfenceRound"};
			case "bagfenceCorner": {"life_inv_bagfenceCorner"};
			case "barGate": {"life_inv_barGate"};
			case "bagBunker": {"life_inv_bagBunker"};
		};
	};
	
	case 1:
	{
		switch (_var) do
		{
			case "life_inv_oilu": {"oilu"};
			case "life_inv_oilp": {"oilp"};
			case "life_inv_heroinu": {"heroinu"};
			case "life_inv_heroinp": {"heroinp"};
			case "life_inv_cannabis": {"cannabis"};
			case "life_inv_marijuana": {"marijuana"};
			case "life_inv_apple": {"apple"};
			case "life_inv_water": {"water"};
			case "life_inv_rabbit": {"rabbit"};
			case "life_inv_salema": {"salema"};
			case "life_inv_ornate": {"ornate"};
			case "life_inv_mackerel": {"mackerel"};
			case "life_inv_tuna": {"tuna"};
			case "life_inv_mullet": {"mullet"};
			case "life_inv_catshark": {"catshark"};
			case "life_inv_turtle": {"turtle"};
			case "life_inv_fishingpoles": {"fishing"};
			case "life_inv_coffee": {"coffee"};
			case "life_inv_turtlesoup": {"turtlesoup"};
			case "life_inv_donuts": {"donuts"};
			case "life_inv_fuelE": {"fuelE"};
			case "life_inv_fuelF": {"fuelF"};
			case "life_cash": {"money"};
			case "life_inv_pickaxe": {"pickaxe"};
			case "life_inv_copperore": {"copperore"};
			case "life_inv_ironore": {"ironore"};
			case "life_inv_ironr": {"iron_r"};
			case "life_inv_copperr": {"copper_r"};
			case "life_inv_sand": {"sand"};
			case "life_inv_salt": {"salt"};
			case "life_inv_glass": {"glass"};
			case "life_inv_redgull": {"redgull"};
			case "life_inv_lockpick": {"lockpick"};
			case "life_inv_tbacon": {"tbacon"};
			case "life_inv_peach": {"peach"};
			case "life_inv_diamond": {"diamond"};
			case "life_inv_diamondr": {"diamondc"};
			case "life_inv_saltr": {"salt_r"};
			case "life_inv_coke": {"cocaine"};
			case "life_inv_cokep": {"cocainep"};
			case "life_inv_spikeStrip": {"spikeStrip"};
			case "life_inv_cement": {"cement"};
			case "life_inv_rock": {"rock"};
			case "life_inv_goldbar": {"goldbar"};
			case "life_inv_blastingcharge": {"blastingcharge"};
			case "life_inv_boltcutter": {"boltcutter"};
			case "life_inv_defusekit": {"defusekit"};
			case "life_inv_storagesmall": {"storagesmall"};
			case "life_inv_storagebig": {"storagebig"};
			
			case "life_inv_shovel": {"shovel"};
			case "life_inv_stolenJewelry": {"stolenJewelry"};
			case "life_inv_ziptie": {"ziptie"};
			case "life_inv_burger": {"burger"};
			case "life_inv_sburger": {"sburger"};
			case "life_inv_ffries": {"ffries"};
			case "life_inv_cola": {"cola"};
			case "life_inv_cshake": {"cshake"};
			case "life_inv_cabsav": {"cabsav"};
			case "life_inv_merlot": {"merlot"};
			case "life_inv_shiraz": {"shiraz"};
			case "life_inv_grenache": {"grenache"};
			case "life_inv_pinotnoir": {"pinotnoir"};
			case "life_inv_chardonnay": {"chardonnay"};
			case "life_inv_souvblanc": {"souvblanc"};
			case "life_inv_semillon": {"semillon"};
			case "life_inv_riesling": {"riesling"};
			case "life_inv_guiness": {"guiness"};
			case "life_inv_bwheat": {"bwheat"};
			case "life_inv_cblue": {"cblue"};
			case "life_inv_bmoon": {"bmoon"};
			case "life_inv_sablager": {"sablager"};
			case "life_inv_vbitter": {"vbitter"};
			case "life_inv_tnew": {"tnew"};
			case "life_inv_told": {"told"};
			case "life_inv_clager": {"clager"};
			case "life_inv_cale": {"cale"};
			case "life_inv_oempire": {"oempire"};
			case "life_inv_jaipur": {"jaipur"};
			case "life_inv_spetersburg": {"spetersburg"};
			case "life_inv_hhoney": {"hhoney"};
			case "life_inv_portstout": {"portstout"};
			case "life_inv_sbbitter": {"sbbitter"};
			case "life_inv_moonshine": {"moonshine"};
			case "life_inv_scotch": {"scotch"};
			case "life_inv_whiskey": {"whiskey"};
			case "life_inv_brandy": {"brandy"};
			case "life_inv_vodka": {"vodka"};
			case "life_inv_tequila": {"tequila"};
			case "life_inv_sake": {"sake"};
			case "life_inv_whiterum": {"whiterum"};
			case "life_inv_rum": {"rum"};
			case "life_inv_gin": {"gin"};
			case "life_inv_absinthe": {"absinthe"};
			case "life_inv_roadCone": {"roadCone"};
			case "life_inv_roadBarrier": {"roadBarrier"};
			case "life_inv_cautionTape": {"cautionTape"};
			case "life_inv_campFire": {"campFire"};
			case "life_inv_sleepbagGreen": {"sleepbagGreen"};
			case "life_inv_sleepbagBlue": {"sleepbagBlue"};
			case "life_inv_sleepbagBrown": {"sleepbagBrown"};
			case "life_inv_tentRidge": {"tentRidge"};
			case "life_inv_tentDome": {"tentDome"};
			case "life_inv_portGenerator": {"portGenerator"};
			case "life_inv_bagfenceShort": {"bagfenceShort"};
			case "life_inv_bagfenceLong": {"bagfenceLong"};
			case "life_inv_bagfenceRound": {"bagfenceRound"};
			case "life_inv_bagfenceCorner": {"bagfenceCorner"};
			case "life_inv_barGate": {"barGate"};
			case "life_inv_bagBunker": {"bagBunker"};
		};
	};
};
